
create table persona (
    persona_id int generated by default as identity primary key,
    nome varchar(255),
    email varchar(255),
    telefono varchar (50),
    password varchar(100),
    ruolo_persona varchar(20)
);

create table utente (
    utente_id int generated by default as identity primary key,
    persona_id int,
    inizio_iscrizione date,
    fine_iscrizione date,
    foreign key (persona_id) references persona(persona_id) on delete cascade
);

create table libro (
    libro_id int generated by default as identity primary key,
    titolo varchar(255),
    autore varchar(255),
    isbn varchar(50),
    genere varchar(100),
    editor varchar(255),
    anno_pubblicazione date,
    copie int
);

create table prenotazione (
    prenotazione_id int generated by default as identity primary key ,
    libro_id int,
    utente_id int,
    data_prenotazione date,
    stato varchar(50),
    foreign key (libro_id) references libro(libro_id) on delete cascade,
    foreign key (utente_id) references utente(utente_id) on delete cascade
);

create table movimento_libro (
    movimento_libro_id int generated by default as identity primary key,
    libro_id int,
    utente_id int,
    data_prestito date,
    data_scadenza date,
    data_restituzione date,
    stato varchar(20),
    foreign key (libro_id) references libro(libro_id) on delete cascade,
    foreign key (utente_id) references utente(utente_id) on delete cascade
);

create table finanziatore (
    finanziatore_id int generated by default as identity primary key,
    persona_id int,
    importo_contributo decimal (15,2),
    data_contributo date,
    foreign key (persona_id) references persona(persona_id)
);

create table finanza (
    finanza_id int generated by default as identity primary key,
    tipo varchar(50),
    importo decimal(15,2),
    descrizione varchar(255),
    data_transazione date,
    finanziatore_id int,
    foreign key (finanziatore_id) references finanziatore(finanziatore_id)
);

create table ruolo (
    ruolo_id int generated by default as identity primary key,
    nome_ruolo varchar(20)
);

create table personale (
    personale_id int generated by default as identity primary key,
    data_assunzione date,
    persona_id int,
    ruolo_id int,
    foreign key (persona_id) references persona(persona_id),
    foreign key (ruolo_id) references ruolo(ruolo_id)
);


